# Generated by Django 3.2.5 on 2022-03-19 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('wema', 'WEMA'), ('access', 'ACCESS'), ('stanbic ibtc', 'STANBIC IBTC'), ('guaranty trust', 'GUARANTY TRUST'), ('first', 'FIRST'), ('united bank of Africa', 'UNITED BANK OF AFRICA'), ('other', 'OTHER')], default='WEMA', max_length=100)),
                ('other', models.BooleanField(default=False)),
                ('account_type', models.CharField(choices=[('savings', 'SAVINGS'), ('current', 'CURRENT'), ('government', 'GOVERNTMENT'), ('motgage', 'MORTGAGE'), ('savings', 'STUDENT'), ('kids', 'KIDS')], default='SAVINGS', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('first_name', models.CharField(default='user', max_length=100)),
                ('last_name', models.CharField(default='user', max_length=100)),
                ('username', models.CharField(default='user', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='MALE', max_length=100)),
                ('profile_picture', models.ImageField(default='user.jpeg', upload_to='')),
                ('date_of_birth', models.DateTimeField(default='2000-05-15')),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bank_information', models.ManyToManyField(to='card_users.Bank')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_users.useraccount'),
        ),
    ]
