# Generated by Django 3.2.5 on 2022-03-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bank',
            name='bvn',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
