# Generated by Django 3.2.5 on 2022-03-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_users', '0002_auto_20220319_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
